### ISSUE TITLE
georeferenced mtl file sets diffuse and ambient to black

### ISSUE THREAD

**Issue by fredlllll** [OpenDroneMap/ODM#597] opened 2017-06-09 12:52 UTC
the mtl file for the georeferenced model sets the diffuse and ambient color to black, while the normal mtl has it set to white.

as the mtl files dont differ otherwise, why isnt it just using the normal one (mtllib odm_textured_model.mtl in obj) or copies the normal one?

**Comment by dakotabenjamin** [comment] 2017-06-09 15:58
I haven't been able to find the source yet, but Ithink it will be in here somewhere: https://github.com/OpenDroneMap/OpenDroneMap/blob/master/modules/odm_georef/src/Georef.cpp#L1099

**Comment by fredlllll** [comment] 2017-06-09 18:07
looked through the code, it doesnt seem to modify the values, but maybe it fails reading them correctly here? https://github.com/OpenDroneMap/OpenDroneMap/blob/master/modules/odm_orthophoto/src/OdmOrthoPhoto.cpp#L1206 

and there is this comment here. is that still up to date? https://github.com/OpenDroneMap/OpenDroneMap/blob/master/modules/odm_orthophoto/src/OdmOrthoPhoto.cpp#L1353

**Comment by yjmenezes** [comment] 2017-06-10 13:48
[Georef301cpp.patch.zip](https://github.com/OpenDroneMap/OpenDroneMap/files/1065861/Georef301cpp.patch.zip)
@dakotabenjamin 

Georef.cpp has some issues.
This patch, over v3.0.1,  is just an output format enhancement and not a bug fix.
The line log_ <<"a)cam.focal_length shows were the gcp_list.txt  measured over original raw images will fail.
To fix it is necessary to replace cam.width by original raw image width.

**Closed as completed** 2020-04-14 19:46 UTC
Labels: software fault
