### ISSUE TITLE
There are many holes in the orthophoto. Is there something wrong with the parameters I set?

### ISSUE THREAD

**Issue by githubhanjunjun** [OpenDroneMap/ODM#1261] opened 2021-04-07 09:15 UTC
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker

### What is the problem?

There are many holes in the orthophoto

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

There is a big difference between the orthophoto I generated and the orthophoto I generated in Webodm

My Orthophoto:

![image](https://user-images.githubusercontent.com/27795864/113841865-bde1ad00-97c4-11eb-97d0-f805f1d2c29f.png)

WebODM Orthophoto:

![image](https://user-images.githubusercontent.com/27795864/113841667-88d55a80-97c4-11eb-83c9-c8262da89d73.png)

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Options:
![image](https://user-images.githubusercontent.com/27795864/113841239-18c6d480-97c4-11eb-8600-d79d695dd01c.png)

I use nodejs to call ODM's run.sh utility and pass in the parameters shown in the figure above

**Comment by pierotofy** [comment] 2021-04-07 20:28
Are you on Windows? It reminds me of this issue: https://github.com/OpenDroneMap/ODM/issues/872 maybe it's related.

**Comment by githubhanjunjun** [comment] 2021-04-08 00:22
> 你在窗户上吗？这让我想起了这个问题[：#872](https://github.com/OpenDroneMap/ODM/issues/872)也许它是相关的。
Webodm and my code run on the same Ubuntu system, but the results are very different

**Comment by githubhanjunjun** [comment] 2021-04-08 00:38
Can you tell me the parameter value that webodm passes when executing ODM's run.sh?

**Comment by githubhanjunjun** [comment] 2021-04-08 00:42
Can you tell me the parameter value that webodm passes when executing ODM's run.sh?

**Comment by pierotofy** [comment] 2021-04-16 20:23
You might be using different versions perhaps? I'm going to close this, as perhaps this is more of a question and not a bug per-se.

Let's move the conversation to the forum if you have questions. :pray:

**Closed as completed by pierotofy** 2021-04-16 20:23 UTC
Labels: possible software fault
