### ISSUE TITLE
3D Projection is generating images with a line

### ISSUE THREAD

**Issue by juvinski** [OpenDroneMap/ODM#721] opened 2017-11-28 19:24 UTC
Hi,

Processing images are resulting in random lines on the final image like this:
![problem1](https://user-images.githubusercontent.com/6621479/33339384-16637eda-d460-11e7-9536-c00a13ab2f84.PNG)
Or
![problem2](https://user-images.githubusercontent.com/6621479/33339394-1de9305a-d460-11e7-9acf-5f0c8a89e615.PNG)
Already change the texturing-data-term but still having problem. 
I see the problem on 3d model too.

**Comment by pierotofy** [comment] 2017-11-29 20:06
I've seen this problem before on other datasets, unfortunately I'm not familiar enough with the mvs_texturing module to say for sure what is the underlying cause. It might be worth to open an issue on https://github.com/nmoehrle/mvs-texturing and ask for help there (at least to get a direction on the possible cause).

**Comment by juvinski** [comment] 2017-11-30 00:01
Hi @pierotofy 
I will do that right now

**Comment by juvinski** [comment] 2019-02-18 18:15
Hi,

just an update. After some tests and research, I could map the main reason of this problem is something on my images. If I run on an images just after the camera shot the pictures, I had this behavior, if I run something to correct the image distortion before the processing, the result is with no lines.

**Comment by smathermather** [comment] 2019-02-22 14:25
@juvinski -- that makes sense. Undistorting would improve the ability of mvs-texturing to map the textures substantially.

I'll mark this as a duplicate of https://github.com/OpenDroneMap/ODM/issues/538 then and close. Thanks for revisiting this!

**Closed as completed by smathermather** 2019-02-22 14:25 UTC
Labels: software fault, duplicate
