### ISSUE TITLE
gcp_list.txt does not support lon,lat coordinates like "EPSG:4326"

### ISSUE THREAD

**Issue by tmizu23** [OpenDroneMap/ODM#693] opened 2017-10-20 09:55 UTC
If gcp_list.txt make lon,lat like "EPSG:4326", the result of orthophoto is broken. 
Probably it is caused by odm_georeferencing process.
Until it is supported, it's better to write it in help.

**Comment by dakotabenjamin** [comment] 2017-10-20 15:35
This is a duplicate of #306

**Closed as completed** 2017-10-20 15:36 UTC
Labels: software fault, duplicate
