### ISSUE TITLE
Fails opensfm_main.py when processing ~2gb worth of imagery

### ISSUE THREAD

**Issue by fosteman** [OpenDroneMap/ODM#1506] opened 2022-07-19 22:06 UTC
How did you install OpenDroneMap? (Docker, natively, ...)?

Docker

What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Ubuntu 20.04 in Google Cloud with Nvidia Tesla T4
16 vCores
104gb RAM

What is the problem?
- /code/SuperBuild/install/bin/opensfm/bin/opensfm_main.py

How can we reproduce this?
Using frontend, uploading ~700 files

[core-dump.txt](https://github.com/OpenDroneMap/ODM/files/9144996/core-dump.txt)

**Comment by fosteman** [comment] 2022-07-19 22:07
`[INFO] Initializing ODM 2.8.8 - Tue Jul 19 21:50:07 2022
[INFO] ==============
[INFO] 3d_tiles: False
[INFO] auto_boundary: False
[INFO] auto_boundary_distance: 0
[INFO] boundary: {}
[INFO] build_overviews: False
[INFO] camera_lens: auto
[INFO] cameras: {}
[INFO] cog: False
[INFO] copy_to: None
[INFO] crop: 3
[INFO] debug: False
[INFO] dem_decimation: 1
[INFO] dem_euclidean_map: False
[INFO] dem_gapfill_steps: 3
[INFO] dem_resolution: 5
[INFO] depthmap_resolution: 640
[INFO] dsm: False
[INFO] dtm: False
[INFO] end_with: odm_postprocess
[INFO] fast_orthophoto: False
[INFO] feature_quality: high
[INFO] feature_type: sift
[INFO] force_gps: False
[INFO] gcp: None
[INFO] geo: None
[INFO] gps_accuracy: 10
[INFO] ignore_gsd: False
[INFO] matcher_neighbors: 0
[INFO] matcher_type: flann
[INFO] max_concurrency: 16
[INFO] merge: all
[INFO] mesh_octree_depth: 11
[INFO] mesh_size: 200000
[INFO] min_num_features: 10000
[INFO] name: 78052c60-3f62-4a3d-b1cd-02f68325d0a0
[INFO] no_gpu: False
[INFO] optimize_disk_space: False
[INFO] orthophoto_compression: DEFLATE
[INFO] orthophoto_cutline: False
[INFO] orthophoto_kmz: False
[INFO] orthophoto_no_tiled: False
[INFO] orthophoto_png: False
[INFO] orthophoto_resolution: 5
[INFO] pc_classify: False
[INFO] pc_copc: False
[INFO] pc_csv: False
[INFO] pc_ept: False
[INFO] pc_filter: 2.5
[INFO] pc_geometric: False
[INFO] pc_las: False
[INFO] pc_quality: medium
[INFO] pc_rectify: False
[INFO] pc_sample: 0
[INFO] pc_tile: False
[INFO] primary_band: auto
[INFO] project_path: /var/www/data
[INFO] radiometric_calibration: none
[INFO] rerun: None
[INFO] rerun_all: False
[INFO] rerun_from: None
[INFO] resize_to: 2048
[INFO] rolling_shutter: False
[INFO] rolling_shutter_readout: 0
[INFO] sfm_algorithm: incremental
[INFO] skip_3dmodel: False
[INFO] skip_band_alignment: False
[INFO] skip_orthophoto: False
[INFO] skip_report: False
[INFO] sky_removal: False
[INFO] sm_cluster: None
[INFO] smrf_scalar: 1.25
[INFO] smrf_slope: 0.15
[INFO] smrf_threshold: 0.5
[INFO] smrf_window: 18.0
[INFO] split: 999999
[INFO] split_image_groups: None
[INFO] split_overlap: 150
[INFO] texturing_data_term: gmi
[INFO] texturing_keep_unseen_faces: False
[INFO] texturing_outlier_removal_type: gauss_clamping
[INFO] texturing_skip_global_seam_leveling: False
[INFO] texturing_skip_local_seam_leveling: False
[INFO] texturing_tone_mapping: none
[INFO] tiles: False
[INFO] time: False
[INFO] use_3dmesh: False
[INFO] use_exif: False
[INFO] use_fixed_camera_params: False
[INFO] use_hybrid_bundle_adjustment: False
[INFO] verbose: False
[INFO] ==============
[INFO] Running dataset stage
[INFO] Loading dataset from: /var/www/data/78052c60-3f62-4a3d-b1cd-02f68325d0a0/images
[INFO] Loading 745 images
[INFO] Wrote images database: /var/www/data/78052c60-3f62-4a3d-b1cd-02f68325d0a0/images.json
[INFO] Found 745 usable images
[INFO] Parsing SRS header: WGS84 UTM 10N
[INFO] Finished dataset stage
[INFO] Running split stage
[INFO] Normal dataset, will process all at once.
[INFO] Finished split stage
[INFO] Running merge stage
[INFO] Normal dataset, nothing to merge.
[INFO] Finished merge stage
[INFO] Running opensfm stage
[INFO] Maximum photo dimensions: 5280px
[INFO] Photo dimensions for feature extraction: 2640px
[INFO] nvidia-smi detected
[INFO] Using GPU for extracting SIFT features
[INFO] Altitude data detected, enabling it for GPS alignment
[INFO] ['use_exif_size: no', 'flann_algorithm: KDTREE', 'feature_process_size: 2640', 'feature_min_frames: 10000', 'processes: 16', 'matching_gps_neighbors: 0', 'matching_gps_distance: 0', 'matching_graph_rounds: 50', 'optimize_camera_parameters: yes', 'reconstruction_algorithm: incremental', 'undistorted_image_format: tif', 'bundle_outlier_filtering_type: AUTO', 'sift_peak_threshold: 0.066', 'align_orientation_prior: vertical', 'triangulation_type: ROBUST', 'retriangulation_ratio: 2', 'matcher_type: FLANN', 'feature_type: SIFT_GPU', 'use_altitude_tag: yes', 'align_method: auto', 'local_bundle_radius: 0']
[INFO] Wrote reference_lla.json
[INFO] running "/code/SuperBuild/install/bin/opensfm/bin/opensfm" detect_features "/var/www/data/78052c60-3f62-4a3d-b1cd-02f68325d0a0/opensfm"
2022-07-19 21:50:25,170 INFO: Planning to use 92342.063671875 MB of RAM for both processing queue and parallel processing.
2022-07-19 21:50:25,171 INFO: Scale-space expected size of a single image : 158.89835357666016 MB
2022-07-19 21:50:25,171 INFO: Expecting to queue at most 200 images while parallel processing of 16 images.
2022-07-19 21:50:25,176 INFO: Reading data for image DJI_0129.JPG (queue-size=0
2022-07-19 21:58:23,590 DEBUG: Matching DJI_0590.JPG and DJI_0611.JPG. Matcher: FLANN (symmetric) T-desc: 6.414 Matches: FAILED
2022-07-19 21:58:23,685 DEBUG: No segmentation for DJI_0198.JPG, no features masked.
2022-07-19 21:58:23,717 DEBUG: Matching DJI_0386.JPG and DJI_0384.JPG. Matcher: FLANN (symmetric) T-desc: 5.268 T-robust: 0.014 T-total: 5.283 Matches: 406 Robust: 224 Success: True
2022-07-19 21:58:23,785 DEBUG: No segmentation for DJI_0134.JPG, no features masked.

.
.
.
.
.
2022-07-19 21:58:24,332 DEBUG: Matching DJI_0374.JPG and DJI_0381.JPG. Matcher: FLANN (symmetric) T-desc: 5.734 Matches: FAILED
Traceback (most recent call last):
File "/code/SuperBuild/install/bin/opensfm/bin/opensfm_main.py", line 25, in
commands.command_runner(
File "/code/SuperBuild/install/bin/opensfm/opensfm/commands/command_runner.py", line 38, in command_runner
command.run(data, args)
File "/code/SuperBuild/install/bin/opensfm/opensfm/commands/command.py", line 13, in run
self.run_impl(data, args)
File "/code/SuperBuild/install/bin/opensfm/opensfm/commands/match_features.py", line 13, in run_impl
match_features.run_dataset(dataset)
File "/code/SuperBuild/install/bin/opensfm/opensfm/actions/match_features.py", line 14, in run_dataset
pairs_matches, preport = matching.match_images(data, {}, images, images)
File "/code/SuperBuild/install/bin/opensfm/opensfm/matching.py", line 56, in match_images
match_images_with_pairs(data, config_override, exifs, pairs),
File "/code/SuperBuild/install/bin/opensfm/opensfm/matching.py", line 80, in match_images_with_pairs
matches = context.parallel_map(match_unwrap_args, args, processes, jobs_per_process)
File "/code/SuperBuild/install/bin/opensfm/opensfm/context.py", line 58, in parallel_map
res = Parallel(batch_size=batch_size)(delayed(func)(arg) for arg in args)
File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1061, in __call__
self.retrieve()
File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 940, in retrieve
self._output.extend(job.get(timeout=self.timeout))
File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
raise self._value
File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 595, in __call__
return self.func(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 262, in __call__
return [func(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 262, in
return [func(*args, **kwargs)
File "/code/SuperBuild/install/bin/opensfm/opensfm/matching.py", line 210, in match_unwrap_args
matches = match(im1, im2, camera1, camera2, data, config_override, pose)
File "/code/SuperBuild/install/bin/opensfm/opensfm/matching.py", line 579, in match
p1, p2, matches, matcher_type = _match_descriptors_impl(
File "/code/SuperBuild/install/bin/opensfm/opensfm/matching.py", line 353, in _match_descriptors_impl
features_data1 = feature_loader.instance.load_all_data(
File "/code/SuperBuild/install/bin/opensfm/opensfm/feature_loading.py", line 109, in load_all_data
features_data = self._load_all_data_masked(data, image)
File "/code/SuperBuild/install/bin/opensfm/opensfm/feature_loading.py", line 160, in _load_all_data_masked
features_data = self._load_all_data_unmasked(data, image)
File "/code/SuperBuild/install/bin/opensfm/opensfm/feature_loading.py", line 154, in _load_all_data_unmasked
return self._load_features_nocache(data, image)
File "/code/SuperBuild/install/bin/opensfm/opensfm/feature_loading.py", line 201, in _load_features_nocache
features_data = data.load_features(image)
File "/code/SuperBuild/install/bin/opensfm/opensfm/dataset.py", line 319, in load_features
return features.FeaturesData.from_file(f, self.config)
File "/code/SuperBuild/install/bin/opensfm/opensfm/features.py", line 140, in from_file
s = np.load(fileobject, allow_pickle=False)
File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 432, in load
ret = NpzFile(fid, own_fid=own_fid, allow_pickle=allow_pickle,
File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 189, in __init__
_zip = zipfile_factory(fid)
File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 112, in zipfile_factory
return zipfile.ZipFile(file, *args, **kwargs)
File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
self._RealGetContents()
File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
terminate called without an active exception
/code/SuperBuild/install/bin/opensfm/bin/opensfm: line 12: 185 Aborted (core dumped) "$PYTHON" "$DIR"/opensfm_main.py "$@"

===== Dumping Info for Geeks (developers need this to fix bugs) =====
Child returned 134
Traceback (most recent call last):
File "/code/stages/odm_app.py", line 94, in execute
self.first_stage.run()
File "/code/opendm/types.py", line 347, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 347, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 347, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 328, in run
self.process(self.args, outputs)
File "/code/stages/run_opensfm.py", line 35, in process
octx.feature_matching(self.rerun())
File "/code/opendm/osfm.py", line 414, in feature_matching
self.match_features(rerun)
File "/code/opendm/osfm.py", line 419, in match_features
self.run('match_features')
File "/code/opendm/osfm.py", line 34, in run
system.run('"%s" %s "%s"' %
File "/code/opendm/system.py", line 106, in run
raise SubprocessException("Child returned {}".format(retcode), retcode)
opendm.system.SubprocessException: Child returned 134

===== Done, human-readable information to follow... =====

[ERROR] Uh oh! Processing stopped because of strange values in the reconstruction. This is often a sign that the input data has some issues or the software cannot deal with it. Have you followed best practices for data acquisition? See https://docs.opendronemap.org/flying/`

**Comment by pierotofy** [comment] 2022-07-22 03:46
Thanks for all the information.

I think based on the log SIFT_GPU is crashing at some point, which falls back to the CPU algorithm, however since the two are not interchangeable, we end up with half SIFT_GPU features and half SIFT, which the matcher doesn't really like.

I pushed a partial fix which at least cleans up any previous result from GPU processing, which gets the software to complete processing, although it's not a good solution, since we should really try to understand why SIFT GPU is crashing to begin with..

**Comment by pierotofy** [comment] 2022-07-22 04:06
It would be super-useful to get a copy of the core dump here (I'm unfortunately unable to reproduce this on my machine).

```
/code/SuperBuild/install/bin/opensfm/bin/opensfm: line 12: 66 Segmentation fault (core dumped) "$PYTHON" "$DIR"/opensfm_main.py "$@"
```

**Comment by Johnny555555** [comment] 2022-07-22 11:00
Ok here's my 19GB core dump file for you to download:
https://1drv.ms/u/s!AnbQHcX3KX2dhat3L0VbX0bgr1EPwg?e=nL9Z10

My system:
Ubuntu 20.4 LTS
HP Proliant DL380P
Dual Intel Xeon 20-core CPUs
512GB RAM
Nvidia K80 GPU (dual GPUs with 12GB RAM each)
1.5TB swap file
RAID (magnetic disks)

Data set:
Almost 7400 images at 20MPx (taken using a P4RTK)
90 GCPs

WebODM project task Settings:
auto-boundary: true, debug: true, dsm: true, dtm: true, smrf-threshold: 0.01, verbose: true

**Comment by pierotofy** [comment] 2022-07-22 15:00
Thanks @Johnny555555 :+1: can you push to docker hub your current docker image you used to generate the core dump? Or can you re-generate it by making sure to use this image? `opendronemap/odm:gpucore`

I tried to open the core file but I think I must be using a different build/version.

**Comment by Johnny555555** [comment] 2022-07-22 23:20
@pierotofy  
I downloaded the gpucore image but when I try to start it, it just exits immediately. Note that my server is running Ubuntu 20.4 LTS.

I am using this nodeodm:gpu image:
REPOSITORY                   TAG       IMAGE ID       CREATED         SIZE
opendronemap/nodeodm         gpu       05d97fae601d   2 months ago    5.88GB
which I installed using this command:
>docker run -dp 3001:3000 --gpus all --name nodeodmgpu opendronemap/nodeodm:gpu

I've pushed it to a public image in Docker Hub:
johnny555555/nodeodmgpu:nodeodmgpu_badzipfile_error

Let me know if you can access it.

**Comment by pierotofy** [comment] 2022-07-23 03:44
Got it, thank you.

I unfortunately wasn't able to open it. gdb keeps complaining. I also realized this is the core dump for the match_features command, which is not the root cause of the issue.

I think this is going to take too long to sort out this way. What would be needed is a small test case that can be reproduced quickly (and possibly, on multiple machines).

**Comment by fosteman** [comment] 2022-07-23 12:55
I'll dump the core and send it your way later today @pierotofy !

**Comment by fosteman** [comment] 2022-07-23 12:56
Here's the dataset of imagery I was trying to put through the standard settings of NodeODM:gpu

https://drive.google.com/drive/folders/1wCyE03UPRk5dwmQ35D20e9MrS4ClRkZt?usp=sharing

**Comment by fosteman** [comment] 2022-07-23 21:01
> [core-dump.txt](https://github.com/OpenDroneMap/ODM/files/9144996/core-dump.txt)

@pierotofy

**Comment by pierotofy** [comment] 2022-07-24 15:40
I was able to reproduce a segfault crash using a small module: https://gist.github.com/pierotofy/1277574c3a7fe4bab102a7dd4279f695

I was then able to fix the segmentation fault with the changes in https://github.com/OpenDroneMap/pypopsift/commit/96910582fa370eb2f166aff5d73a4e6c29dfdb57

I've committed https://github.com/OpenDroneMap/ODM/commit/55a7821058229cab735e2447daa83a86ff65e7cd which *should* fix this issue. If it works, there should be no warnings about failed GPU SIFT extraction and processing should continue to completion.

Please wait until the new GPU docker image is updated and try again? :pray:

**Comment by fosteman** [comment] 2022-07-25 14:09
Awesome, @pierotofy , the issue resolved. Though after the feature extraction is done, it takes superbly long time to actually reconstruct the images and it's only doing it 1 core at a time. I'm running a 16 core VM. Any way to improve that ? 
`Concurrency` is set to 16. 
Am I missing something ?

**Closed as completed** 2022-07-25 14:45 UTC
Labels: possible software fault

**Comment by pierotofy** [comment] 2022-07-25 15:06
Some parts of the pipeline are single threaded, other parts are multi-threaded. There's probably not much you can do. Glad the issue is fixed! Thanks for the reports and core dumps.

**Comment by Johnny555555** [comment] 2022-07-25 22:10
Thanks Piero, much appreciated for the fix!
