### ISSUE TITLE
Coordinate string out of reference?

### ISSUE THREAD

**Issue by MilesSpathelf** [OpenDroneMap/ODM#707] opened 2017-11-09 20:38 UTC
Hello,

I'm analyzing some drone imagery in Alaska and I came across this error:

[INFO]    Running ODM Texturing Cell - Finished
[INFO]    Running ODM Georeferencing Cell
[DEBUG]   None
[WARNING] No coordinates file. Generating coordinates file: /var/www/data/eab317a2-2d67-4521-8fd0-1da59970b125/odm_georeferencing/coords.txt

[INFO]    Running georeferencing with generated coords file.
[DEBUG]   running /code/build/bin/odm_georef -bundleFile /var/www/data/eab317a2-2d67-4521-8fd0-1da59970b125/opensfm/bundle_r000.out -inputCoordFile /var/www/data/eab317a2-2d67-4521-8fd0-1da59970b125/odm_georeferencing/coords.txt -inputFile /var/www/data/eab317a2-2d67-4521-8fd0-1da59970b125/odm_texturing/odm_textured_model.obj -outputFile /var/www/data/eab317a2-2d67-4521-8fd0-1da59970b125/odm_texturing/odm_textured_model_geo.obj -inputPointCloudFile /var/www/data/eab317a2-2d67-4521-8fd0-1da59970b125/pmvs/recon0/models/option-0000.ply -outputPointCloudFile /var/www/data/eab317a2-2d67-4521-8fd0-1da59970b125/odm_georeferencing/odm_georeferenced_model.ply  -logFile /var/www/data/eab317a2-2d67-4521-8fd0-1da59970b125/odm_georeferencing/odm_georeferencing_log.txt -outputTransformFile /var/www/data/eab317a2-2d67-4521-8fd0-1da59970b125/odm_georeferencing/odm_georeferencing_transform.txt -georefFileOutputPath /var/www/data/eab317a2-2d67-4521-8fd0-1da59970b125/odm_georeferencing/odm_georeferencing_model_geo.txt

  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/odm_georeferencing.py", line 162, in process
    geo_ref.parse_coordinate_system(tree.odm_georeferencing_coords)
  File "/code/opendm/types.py", line 317, in parse_coordinate_system
    self.utm_pole = ref[2][len(ref) - 1]
IndexError: string index out of range

It seems as if my coordinates are out of range?  Is Alaska not supported for ODM?
[task_output.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1459107/task_output.txt)

**Comment by dakotabenjamin** [comment] 2017-11-09 20:46
Hi, this is a duplicate of #698

**Comment by MilesSpathelf** [comment] 2017-11-09 20:47
Oh, ok thanks.  I didn't see that one.  So this is an ongoing error?

**Comment by dakotabenjamin** [comment] 2017-11-09 20:49
Yeah, check out here: https://github.com/OpenDroneMap/WebODM/issues/303 the fix has been added to the master branch

**Comment by MilesSpathelf** [comment] 2017-11-09 20:52
Hmm... I just updated via the WebODM interface before I started the run.  Is there another update I have to intstall?

**Comment by dakotabenjamin** [comment] 2017-11-09 20:55
you probably have to update your node-odm as well.

**Comment by MilesSpathelf** [comment] 2017-11-09 20:58
I apologize for my ignorance...  here is my node status as found through the WebODM interface


Hostname | node-odm-1
-- | --
Port | 3000
API Version | 1.0.3
Queue Count | 0
Last Refreshed | 0 minutes ago (Nov. 9, 2017, 8:56 p.m.)

**Comment by pierotofy** [comment] 2017-11-09 22:34
Hi @MilesSpathelf, perhaps this is a different bug; any chance you could share the dataset (or a subset of it) either privately or publicly via Dropbox/Google Drive? The error looks the same as #698, but if you've updated node-odm to the latest version perhaps this is something new.

**Comment by pierotofy** [comment] 2017-11-10 02:39
Can confirm, this is a bug.

Code will fail with `WGS84 UTM 6N`:

```python
            line = 'WGS84 UTM 6N'
            log.ODM_DEBUG('Line: %s' % line)
            ref = line.split(' ')
            # match_wgs_utm = re.search('WGS84 UTM (\d{1,2})(N|S)', line, re.I)
            if ref[0] == 'WGS84' and ref[1] == 'UTM':  # match_wgs_utm:
                self.datum = ref[0]
                self.utm_pole = ref[2][len(ref) - 1]
```

Incriminating line is `ref[2][len(ref) - 1]`. Will open a PR for this by tomorrow.

**Comment by MilesSpathelf** [comment] 2017-11-10 03:01
Ah, many thanks for the confirmation!  Cheers,

Miles

**Closed as completed** 2017-11-20 21:17 UTC
Labels: software fault

**Comment by MilesSpathelf** [comment] 2017-11-22 20:06
Just wanted to say the update fixed my problem.  Many thanks!

**Comment by pierotofy** [comment] 2017-11-22 20:27
Ace 👍 you're welcome!
