### ISSUE TITLE
NameError: name 'sift' is not defined

### ISSUE THREAD

**Issue by pdrlsoftwareteam** [OpenDroneMap/ODM#1420] opened 2022-02-22 19:15 UTC
i  installed OpenDroneMap Natively
using https://github.com/OpenDroneMap/ODM) on ubuntu, getting
NameError: name 'sift' is not defined
getting this error when   running on vm with k80 gpu.
ideally  it should generate orthomosaic
i did the conda activation wth python 3.8.10 and opencv 4.5.5 on ubuntu 20.04
conda activate
and run  ./run.sh -project_path datasets/test1 -id test1

**Comment by pierotofy** [comment] 2022-02-25 21:04
I wouldn't recommend to install ODM natively, but if you're getting import errors something didn't go well in the process of building it. Follow the `Dockerfile` for exact commands and don't use conda, it's not part of our standard build process.

I'm going to close this since it's not a bug :pray: if you have further questions let's move the conversation over to https://community.opendronemap.org

**Closed as completed by pierotofy** 2022-02-25 21:04 UTC
